apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
stringData:
  GMAIL_ADDRESS: "charisnnadi15@gmail.com" #enter your email to get the id
  GMAIL_PASSWORD: "password" #enter your email app-password
type: Opaque
